# General
jwt.secretKey=MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMDEyMzQ1Njc4OTA=
frontend.url=http://localhost:4200

# Database-related
spring.datasource.username=root
spring.datasource.password=Vindel39!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true