package dev.jcasaslopez.booking.filter;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import dev.jcasaslopez.booking.base.BaseIntegrationTest;
import dev.jcasaslopez.booking.dto.BookingRequestDto;
import dev.jcasaslopez.booking.util.Endpoints;
import dev.jcasaslopez.booking.util.TestHelper;

// Happy path and "/searches/" bypass are not tested here: they're already covered by BookEndpointTest 
// (among other protected-endpoint tests), which sends a real JWT through this filter, and by 
// FindBookingByEndpointTest (among other unprotected-endpoint tests), which would fail if the bypass broke.

// Inherits BaseIntegrationTest only because Spring Boot needs the full ApplicationContext to start (in particular 
// it needs the bean ClassroomsStore that reads the list of classrooms from the Kafka container), not because this
// test needs that infrastructure.
public class AuthFilterIntegrationTest extends BaseIntegrationTest{
	
	private static final int SLOT_DURATION = 30;
	private static final int CLASSROOM_ID = 1;
	private static final int USER_ID = 1;
	private static final String INVALID_JWT = "Invalid_JWT";
	
	@Test
	void auth_filter_responds_with_401_if_token_is_not_valid() {
		// Arrange
		BookingRequestDto bookingDto = new BookingRequestDto(USER_ID, CLASSROOM_ID, TestHelper.generateBookingSlots(SLOT_DURATION));

		HttpHeaders headers = new HttpHeaders();
		headers.setBearerAuth(INVALID_JWT);
		HttpEntity<BookingRequestDto> httpBookingRequest = new HttpEntity<>(bookingDto, headers);

		// Act
		// We use String.class for the ResponseEntity body, as Jackson does not have information about the date 
		// format for the timestamp generated by BasicErrorController. 
		//
		// Spring Boot's default error payload structure:
		// JSON:{
		// 		"timestamp": "2026-06-18T...",
		// 		"status": 401,
		// 		"error": "Unauthorized",
		// 		"path": ...
		// 		}
		ResponseEntity<String> httpResponse = testRestTemplate.exchange(
				Endpoints.BOOK, 
				HttpMethod.POST, 
				httpBookingRequest, 
				String.class 
				);
		
		System.out.println(httpResponse);
		
		// Assert
		// Note: The message returned by default by Spring Boot is "Unauthorized" due to security configurations,
		// rather than the custom "Authentication failed" string manually set in the filter response.
		assertAll(
		        () -> assertEquals(HttpStatus.UNAUTHORIZED, httpResponse.getStatusCode()),
		        () -> assertTrue(httpResponse.getBody().contains("Unauthorized")) 
		       );
	}
}
